package com.jemmyee.inf.entity;

import com.jemmyee.core.entity.BaseExample;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AccountExample extends BaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INF_ACCOUNT
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INF_ACCOUNT
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INF_ACCOUNT
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF_ACCOUNT
     *
     * @mbggenerated
     */
    public AccountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF_ACCOUNT
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF_ACCOUNT
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF_ACCOUNT
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF_ACCOUNT
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF_ACCOUNT
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF_ACCOUNT
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF_ACCOUNT
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF_ACCOUNT
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF_ACCOUNT
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF_ACCOUNT
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INF_ACCOUNT
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRecordidIsNull() {
            addCriterion("RECORDID is null");
            return (Criteria) this;
        }

        public Criteria andRecordidIsNotNull() {
            addCriterion("RECORDID is not null");
            return (Criteria) this;
        }

        public Criteria andRecordidEqualTo(String value) {
            addCriterion("RECORDID =", value, "recordid");
            return (Criteria) this;
        }

        public Criteria andRecordidNotEqualTo(String value) {
            addCriterion("RECORDID <>", value, "recordid");
            return (Criteria) this;
        }

        public Criteria andRecordidGreaterThan(String value) {
            addCriterion("RECORDID >", value, "recordid");
            return (Criteria) this;
        }

        public Criteria andRecordidGreaterThanOrEqualTo(String value) {
            addCriterion("RECORDID >=", value, "recordid");
            return (Criteria) this;
        }

        public Criteria andRecordidLessThan(String value) {
            addCriterion("RECORDID <", value, "recordid");
            return (Criteria) this;
        }

        public Criteria andRecordidLessThanOrEqualTo(String value) {
            addCriterion("RECORDID <=", value, "recordid");
            return (Criteria) this;
        }

        public Criteria andRecordidLike(String value) {
            addCriterion("RECORDID like", value, "recordid");
            return (Criteria) this;
        }

        public Criteria andRecordidNotLike(String value) {
            addCriterion("RECORDID not like", value, "recordid");
            return (Criteria) this;
        }

        public Criteria andRecordidIn(List<String> values) {
            addCriterion("RECORDID in", values, "recordid");
            return (Criteria) this;
        }

        public Criteria andRecordidNotIn(List<String> values) {
            addCriterion("RECORDID not in", values, "recordid");
            return (Criteria) this;
        }

        public Criteria andRecordidBetween(String value1, String value2) {
            addCriterion("RECORDID between", value1, value2, "recordid");
            return (Criteria) this;
        }

        public Criteria andRecordidNotBetween(String value1, String value2) {
            addCriterion("RECORDID not between", value1, value2, "recordid");
            return (Criteria) this;
        }

        public Criteria andCompanycodeIsNull() {
            addCriterion("COMPANYCODE is null");
            return (Criteria) this;
        }

        public Criteria andCompanycodeIsNotNull() {
            addCriterion("COMPANYCODE is not null");
            return (Criteria) this;
        }

        public Criteria andCompanycodeEqualTo(String value) {
            addCriterion("COMPANYCODE =", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeNotEqualTo(String value) {
            addCriterion("COMPANYCODE <>", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeGreaterThan(String value) {
            addCriterion("COMPANYCODE >", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeGreaterThanOrEqualTo(String value) {
            addCriterion("COMPANYCODE >=", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeLessThan(String value) {
            addCriterion("COMPANYCODE <", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeLessThanOrEqualTo(String value) {
            addCriterion("COMPANYCODE <=", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeLike(String value) {
            addCriterion("COMPANYCODE like", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeNotLike(String value) {
            addCriterion("COMPANYCODE not like", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeIn(List<String> values) {
            addCriterion("COMPANYCODE in", values, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeNotIn(List<String> values) {
            addCriterion("COMPANYCODE not in", values, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeBetween(String value1, String value2) {
            addCriterion("COMPANYCODE between", value1, value2, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeNotBetween(String value1, String value2) {
            addCriterion("COMPANYCODE not between", value1, value2, "companycode");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("CODE is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("CODE =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("CODE <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("CODE >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CODE >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("CODE <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("CODE <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("CODE like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("CODE not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("CODE in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("CODE not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("CODE between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("CODE not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andPlateIsNull() {
            addCriterion("PLATE is null");
            return (Criteria) this;
        }

        public Criteria andPlateIsNotNull() {
            addCriterion("PLATE is not null");
            return (Criteria) this;
        }

        public Criteria andPlateEqualTo(String value) {
            addCriterion("PLATE =", value, "plate");
            return (Criteria) this;
        }

        public Criteria andPlateNotEqualTo(String value) {
            addCriterion("PLATE <>", value, "plate");
            return (Criteria) this;
        }

        public Criteria andPlateGreaterThan(String value) {
            addCriterion("PLATE >", value, "plate");
            return (Criteria) this;
        }

        public Criteria andPlateGreaterThanOrEqualTo(String value) {
            addCriterion("PLATE >=", value, "plate");
            return (Criteria) this;
        }

        public Criteria andPlateLessThan(String value) {
            addCriterion("PLATE <", value, "plate");
            return (Criteria) this;
        }

        public Criteria andPlateLessThanOrEqualTo(String value) {
            addCriterion("PLATE <=", value, "plate");
            return (Criteria) this;
        }

        public Criteria andPlateLike(String value) {
            addCriterion("PLATE like", value, "plate");
            return (Criteria) this;
        }

        public Criteria andPlateNotLike(String value) {
            addCriterion("PLATE not like", value, "plate");
            return (Criteria) this;
        }

        public Criteria andPlateIn(List<String> values) {
            addCriterion("PLATE in", values, "plate");
            return (Criteria) this;
        }

        public Criteria andPlateNotIn(List<String> values) {
            addCriterion("PLATE not in", values, "plate");
            return (Criteria) this;
        }

        public Criteria andPlateBetween(String value1, String value2) {
            addCriterion("PLATE between", value1, value2, "plate");
            return (Criteria) this;
        }

        public Criteria andPlateNotBetween(String value1, String value2) {
            addCriterion("PLATE not between", value1, value2, "plate");
            return (Criteria) this;
        }

        public Criteria andPlatecolorIsNull() {
            addCriterion("PLATECOLOR is null");
            return (Criteria) this;
        }

        public Criteria andPlatecolorIsNotNull() {
            addCriterion("PLATECOLOR is not null");
            return (Criteria) this;
        }

        public Criteria andPlatecolorEqualTo(BigDecimal value) {
            addCriterion("PLATECOLOR =", value, "platecolor");
            return (Criteria) this;
        }

        public Criteria andPlatecolorNotEqualTo(BigDecimal value) {
            addCriterion("PLATECOLOR <>", value, "platecolor");
            return (Criteria) this;
        }

        public Criteria andPlatecolorGreaterThan(BigDecimal value) {
            addCriterion("PLATECOLOR >", value, "platecolor");
            return (Criteria) this;
        }

        public Criteria andPlatecolorGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PLATECOLOR >=", value, "platecolor");
            return (Criteria) this;
        }

        public Criteria andPlatecolorLessThan(BigDecimal value) {
            addCriterion("PLATECOLOR <", value, "platecolor");
            return (Criteria) this;
        }

        public Criteria andPlatecolorLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PLATECOLOR <=", value, "platecolor");
            return (Criteria) this;
        }

        public Criteria andPlatecolorIn(List<BigDecimal> values) {
            addCriterion("PLATECOLOR in", values, "platecolor");
            return (Criteria) this;
        }

        public Criteria andPlatecolorNotIn(List<BigDecimal> values) {
            addCriterion("PLATECOLOR not in", values, "platecolor");
            return (Criteria) this;
        }

        public Criteria andPlatecolorBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PLATECOLOR between", value1, value2, "platecolor");
            return (Criteria) this;
        }

        public Criteria andPlatecolorNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PLATECOLOR not between", value1, value2, "platecolor");
            return (Criteria) this;
        }

        public Criteria andIntimeIsNull() {
            addCriterion("INTIME is null");
            return (Criteria) this;
        }

        public Criteria andIntimeIsNotNull() {
            addCriterion("INTIME is not null");
            return (Criteria) this;
        }

        public Criteria andIntimeEqualTo(Date value) {
            addCriterion("INTIME =", value, "intime");
            return (Criteria) this;
        }

        public Criteria andIntimeNotEqualTo(Date value) {
            addCriterion("INTIME <>", value, "intime");
            return (Criteria) this;
        }

        public Criteria andIntimeGreaterThan(Date value) {
            addCriterion("INTIME >", value, "intime");
            return (Criteria) this;
        }

        public Criteria andIntimeGreaterThanOrEqualTo(Date value) {
            addCriterion("INTIME >=", value, "intime");
            return (Criteria) this;
        }

        public Criteria andIntimeLessThan(Date value) {
            addCriterion("INTIME <", value, "intime");
            return (Criteria) this;
        }

        public Criteria andIntimeLessThanOrEqualTo(Date value) {
            addCriterion("INTIME <=", value, "intime");
            return (Criteria) this;
        }

        public Criteria andIntimeIn(List<Date> values) {
            addCriterion("INTIME in", values, "intime");
            return (Criteria) this;
        }

        public Criteria andIntimeNotIn(List<Date> values) {
            addCriterion("INTIME not in", values, "intime");
            return (Criteria) this;
        }

        public Criteria andIntimeBetween(Date value1, Date value2) {
            addCriterion("INTIME between", value1, value2, "intime");
            return (Criteria) this;
        }

        public Criteria andIntimeNotBetween(Date value1, Date value2) {
            addCriterion("INTIME not between", value1, value2, "intime");
            return (Criteria) this;
        }

        public Criteria andPayedcompanycodeIsNull() {
            addCriterion("PAYEDCOMPANYCODE is null");
            return (Criteria) this;
        }

        public Criteria andPayedcompanycodeIsNotNull() {
            addCriterion("PAYEDCOMPANYCODE is not null");
            return (Criteria) this;
        }

        public Criteria andPayedcompanycodeEqualTo(BigDecimal value) {
            addCriterion("PAYEDCOMPANYCODE =", value, "payedcompanycode");
            return (Criteria) this;
        }

        public Criteria andPayedcompanycodeNotEqualTo(BigDecimal value) {
            addCriterion("PAYEDCOMPANYCODE <>", value, "payedcompanycode");
            return (Criteria) this;
        }

        public Criteria andPayedcompanycodeGreaterThan(BigDecimal value) {
            addCriterion("PAYEDCOMPANYCODE >", value, "payedcompanycode");
            return (Criteria) this;
        }

        public Criteria andPayedcompanycodeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PAYEDCOMPANYCODE >=", value, "payedcompanycode");
            return (Criteria) this;
        }

        public Criteria andPayedcompanycodeLessThan(BigDecimal value) {
            addCriterion("PAYEDCOMPANYCODE <", value, "payedcompanycode");
            return (Criteria) this;
        }

        public Criteria andPayedcompanycodeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PAYEDCOMPANYCODE <=", value, "payedcompanycode");
            return (Criteria) this;
        }

        public Criteria andPayedcompanycodeIn(List<BigDecimal> values) {
            addCriterion("PAYEDCOMPANYCODE in", values, "payedcompanycode");
            return (Criteria) this;
        }

        public Criteria andPayedcompanycodeNotIn(List<BigDecimal> values) {
            addCriterion("PAYEDCOMPANYCODE not in", values, "payedcompanycode");
            return (Criteria) this;
        }

        public Criteria andPayedcompanycodeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAYEDCOMPANYCODE between", value1, value2, "payedcompanycode");
            return (Criteria) this;
        }

        public Criteria andPayedcompanycodeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAYEDCOMPANYCODE not between", value1, value2, "payedcompanycode");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("USERID is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("USERID is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(String value) {
            addCriterion("USERID =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(String value) {
            addCriterion("USERID <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(String value) {
            addCriterion("USERID >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(String value) {
            addCriterion("USERID >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(String value) {
            addCriterion("USERID <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(String value) {
            addCriterion("USERID <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLike(String value) {
            addCriterion("USERID like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotLike(String value) {
            addCriterion("USERID not like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<String> values) {
            addCriterion("USERID in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<String> values) {
            addCriterion("USERID not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(String value1, String value2) {
            addCriterion("USERID between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(String value1, String value2) {
            addCriterion("USERID not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(BigDecimal value) {
            addCriterion("TYPE =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(BigDecimal value) {
            addCriterion("TYPE <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(BigDecimal value) {
            addCriterion("TYPE >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TYPE >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(BigDecimal value) {
            addCriterion("TYPE <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TYPE <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<BigDecimal> values) {
            addCriterion("TYPE in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<BigDecimal> values) {
            addCriterion("TYPE not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TYPE between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TYPE not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(BigDecimal value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(BigDecimal value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(BigDecimal value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(BigDecimal value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(BigDecimal value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<BigDecimal> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<BigDecimal> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andBalanceIsNull() {
            addCriterion("BALANCE is null");
            return (Criteria) this;
        }

        public Criteria andBalanceIsNotNull() {
            addCriterion("BALANCE is not null");
            return (Criteria) this;
        }

        public Criteria andBalanceEqualTo(BigDecimal value) {
            addCriterion("BALANCE =", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceNotEqualTo(BigDecimal value) {
            addCriterion("BALANCE <>", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceGreaterThan(BigDecimal value) {
            addCriterion("BALANCE >", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BALANCE >=", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceLessThan(BigDecimal value) {
            addCriterion("BALANCE <", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BALANCE <=", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceIn(List<BigDecimal> values) {
            addCriterion("BALANCE in", values, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceNotIn(List<BigDecimal> values) {
            addCriterion("BALANCE not in", values, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BALANCE between", value1, value2, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BALANCE not between", value1, value2, "balance");
            return (Criteria) this;
        }

        public Criteria andIscararrearIsNull() {
            addCriterion("ISCARARREAR is null");
            return (Criteria) this;
        }

        public Criteria andIscararrearIsNotNull() {
            addCriterion("ISCARARREAR is not null");
            return (Criteria) this;
        }

        public Criteria andIscararrearEqualTo(BigDecimal value) {
            addCriterion("ISCARARREAR =", value, "iscararrear");
            return (Criteria) this;
        }

        public Criteria andIscararrearNotEqualTo(BigDecimal value) {
            addCriterion("ISCARARREAR <>", value, "iscararrear");
            return (Criteria) this;
        }

        public Criteria andIscararrearGreaterThan(BigDecimal value) {
            addCriterion("ISCARARREAR >", value, "iscararrear");
            return (Criteria) this;
        }

        public Criteria andIscararrearGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ISCARARREAR >=", value, "iscararrear");
            return (Criteria) this;
        }

        public Criteria andIscararrearLessThan(BigDecimal value) {
            addCriterion("ISCARARREAR <", value, "iscararrear");
            return (Criteria) this;
        }

        public Criteria andIscararrearLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ISCARARREAR <=", value, "iscararrear");
            return (Criteria) this;
        }

        public Criteria andIscararrearIn(List<BigDecimal> values) {
            addCriterion("ISCARARREAR in", values, "iscararrear");
            return (Criteria) this;
        }

        public Criteria andIscararrearNotIn(List<BigDecimal> values) {
            addCriterion("ISCARARREAR not in", values, "iscararrear");
            return (Criteria) this;
        }

        public Criteria andIscararrearBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ISCARARREAR between", value1, value2, "iscararrear");
            return (Criteria) this;
        }

        public Criteria andIscararrearNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ISCARARREAR not between", value1, value2, "iscararrear");
            return (Criteria) this;
        }

        public Criteria andCararrearamountIsNull() {
            addCriterion("CARARREARAMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andCararrearamountIsNotNull() {
            addCriterion("CARARREARAMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andCararrearamountEqualTo(BigDecimal value) {
            addCriterion("CARARREARAMOUNT =", value, "cararrearamount");
            return (Criteria) this;
        }

        public Criteria andCararrearamountNotEqualTo(BigDecimal value) {
            addCriterion("CARARREARAMOUNT <>", value, "cararrearamount");
            return (Criteria) this;
        }

        public Criteria andCararrearamountGreaterThan(BigDecimal value) {
            addCriterion("CARARREARAMOUNT >", value, "cararrearamount");
            return (Criteria) this;
        }

        public Criteria andCararrearamountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CARARREARAMOUNT >=", value, "cararrearamount");
            return (Criteria) this;
        }

        public Criteria andCararrearamountLessThan(BigDecimal value) {
            addCriterion("CARARREARAMOUNT <", value, "cararrearamount");
            return (Criteria) this;
        }

        public Criteria andCararrearamountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CARARREARAMOUNT <=", value, "cararrearamount");
            return (Criteria) this;
        }

        public Criteria andCararrearamountIn(List<BigDecimal> values) {
            addCriterion("CARARREARAMOUNT in", values, "cararrearamount");
            return (Criteria) this;
        }

        public Criteria andCararrearamountNotIn(List<BigDecimal> values) {
            addCriterion("CARARREARAMOUNT not in", values, "cararrearamount");
            return (Criteria) this;
        }

        public Criteria andCararrearamountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CARARREARAMOUNT between", value1, value2, "cararrearamount");
            return (Criteria) this;
        }

        public Criteria andCararrearamountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CARARREARAMOUNT not between", value1, value2, "cararrearamount");
            return (Criteria) this;
        }

        public Criteria andIsacctarrearIsNull() {
            addCriterion("ISACCTARREAR is null");
            return (Criteria) this;
        }

        public Criteria andIsacctarrearIsNotNull() {
            addCriterion("ISACCTARREAR is not null");
            return (Criteria) this;
        }

        public Criteria andIsacctarrearEqualTo(BigDecimal value) {
            addCriterion("ISACCTARREAR =", value, "isacctarrear");
            return (Criteria) this;
        }

        public Criteria andIsacctarrearNotEqualTo(BigDecimal value) {
            addCriterion("ISACCTARREAR <>", value, "isacctarrear");
            return (Criteria) this;
        }

        public Criteria andIsacctarrearGreaterThan(BigDecimal value) {
            addCriterion("ISACCTARREAR >", value, "isacctarrear");
            return (Criteria) this;
        }

        public Criteria andIsacctarrearGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ISACCTARREAR >=", value, "isacctarrear");
            return (Criteria) this;
        }

        public Criteria andIsacctarrearLessThan(BigDecimal value) {
            addCriterion("ISACCTARREAR <", value, "isacctarrear");
            return (Criteria) this;
        }

        public Criteria andIsacctarrearLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ISACCTARREAR <=", value, "isacctarrear");
            return (Criteria) this;
        }

        public Criteria andIsacctarrearIn(List<BigDecimal> values) {
            addCriterion("ISACCTARREAR in", values, "isacctarrear");
            return (Criteria) this;
        }

        public Criteria andIsacctarrearNotIn(List<BigDecimal> values) {
            addCriterion("ISACCTARREAR not in", values, "isacctarrear");
            return (Criteria) this;
        }

        public Criteria andIsacctarrearBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ISACCTARREAR between", value1, value2, "isacctarrear");
            return (Criteria) this;
        }

        public Criteria andIsacctarrearNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ISACCTARREAR not between", value1, value2, "isacctarrear");
            return (Criteria) this;
        }

        public Criteria andAcctarrearamountIsNull() {
            addCriterion("ACCTARREARAMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andAcctarrearamountIsNotNull() {
            addCriterion("ACCTARREARAMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andAcctarrearamountEqualTo(BigDecimal value) {
            addCriterion("ACCTARREARAMOUNT =", value, "acctarrearamount");
            return (Criteria) this;
        }

        public Criteria andAcctarrearamountNotEqualTo(BigDecimal value) {
            addCriterion("ACCTARREARAMOUNT <>", value, "acctarrearamount");
            return (Criteria) this;
        }

        public Criteria andAcctarrearamountGreaterThan(BigDecimal value) {
            addCriterion("ACCTARREARAMOUNT >", value, "acctarrearamount");
            return (Criteria) this;
        }

        public Criteria andAcctarrearamountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ACCTARREARAMOUNT >=", value, "acctarrearamount");
            return (Criteria) this;
        }

        public Criteria andAcctarrearamountLessThan(BigDecimal value) {
            addCriterion("ACCTARREARAMOUNT <", value, "acctarrearamount");
            return (Criteria) this;
        }

        public Criteria andAcctarrearamountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ACCTARREARAMOUNT <=", value, "acctarrearamount");
            return (Criteria) this;
        }

        public Criteria andAcctarrearamountIn(List<BigDecimal> values) {
            addCriterion("ACCTARREARAMOUNT in", values, "acctarrearamount");
            return (Criteria) this;
        }

        public Criteria andAcctarrearamountNotIn(List<BigDecimal> values) {
            addCriterion("ACCTARREARAMOUNT not in", values, "acctarrearamount");
            return (Criteria) this;
        }

        public Criteria andAcctarrearamountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACCTARREARAMOUNT between", value1, value2, "acctarrearamount");
            return (Criteria) this;
        }

        public Criteria andAcctarrearamountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACCTARREARAMOUNT not between", value1, value2, "acctarrearamount");
            return (Criteria) this;
        }

        public Criteria andPlatformuserinfoIsNull() {
            addCriterion("PLATFORMUSERINFO is null");
            return (Criteria) this;
        }

        public Criteria andPlatformuserinfoIsNotNull() {
            addCriterion("PLATFORMUSERINFO is not null");
            return (Criteria) this;
        }

        public Criteria andPlatformuserinfoEqualTo(String value) {
            addCriterion("PLATFORMUSERINFO =", value, "platformuserinfo");
            return (Criteria) this;
        }

        public Criteria andPlatformuserinfoNotEqualTo(String value) {
            addCriterion("PLATFORMUSERINFO <>", value, "platformuserinfo");
            return (Criteria) this;
        }

        public Criteria andPlatformuserinfoGreaterThan(String value) {
            addCriterion("PLATFORMUSERINFO >", value, "platformuserinfo");
            return (Criteria) this;
        }

        public Criteria andPlatformuserinfoGreaterThanOrEqualTo(String value) {
            addCriterion("PLATFORMUSERINFO >=", value, "platformuserinfo");
            return (Criteria) this;
        }

        public Criteria andPlatformuserinfoLessThan(String value) {
            addCriterion("PLATFORMUSERINFO <", value, "platformuserinfo");
            return (Criteria) this;
        }

        public Criteria andPlatformuserinfoLessThanOrEqualTo(String value) {
            addCriterion("PLATFORMUSERINFO <=", value, "platformuserinfo");
            return (Criteria) this;
        }

        public Criteria andPlatformuserinfoLike(String value) {
            addCriterion("PLATFORMUSERINFO like", value, "platformuserinfo");
            return (Criteria) this;
        }

        public Criteria andPlatformuserinfoNotLike(String value) {
            addCriterion("PLATFORMUSERINFO not like", value, "platformuserinfo");
            return (Criteria) this;
        }

        public Criteria andPlatformuserinfoIn(List<String> values) {
            addCriterion("PLATFORMUSERINFO in", values, "platformuserinfo");
            return (Criteria) this;
        }

        public Criteria andPlatformuserinfoNotIn(List<String> values) {
            addCriterion("PLATFORMUSERINFO not in", values, "platformuserinfo");
            return (Criteria) this;
        }

        public Criteria andPlatformuserinfoBetween(String value1, String value2) {
            addCriterion("PLATFORMUSERINFO between", value1, value2, "platformuserinfo");
            return (Criteria) this;
        }

        public Criteria andPlatformuserinfoNotBetween(String value1, String value2) {
            addCriterion("PLATFORMUSERINFO not between", value1, value2, "platformuserinfo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INF_ACCOUNT
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INF_ACCOUNT
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}