package com.jemmyee.inf.entity;

import com.jemmyee.core.entity.BaseEntity;

import java.math.BigDecimal;
import java.util.Date;

public class Account extends BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF_ACCOUNT.RECORDID
     *
     * @mbggenerated
     */
    private String recordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF_ACCOUNT.COMPANYCODE
     *
     * @mbggenerated
     */
    private String companycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF_ACCOUNT.CODE
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF_ACCOUNT.PLATE
     *
     * @mbggenerated
     */
    private String plate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF_ACCOUNT.PLATECOLOR
     *
     * @mbggenerated
     */
    private BigDecimal platecolor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF_ACCOUNT.INTIME
     *
     * @mbggenerated
     */
    private Date intime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF_ACCOUNT.PAYEDCOMPANYCODE
     *
     * @mbggenerated
     */
    private BigDecimal payedcompanycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF_ACCOUNT.USERID
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF_ACCOUNT.TYPE
     *
     * @mbggenerated
     */
    private BigDecimal type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF_ACCOUNT.STATUS
     *
     * @mbggenerated
     */

    private BigDecimal status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF_ACCOUNT.BALANCE
     *
     * @mbggenerated
     */
    private BigDecimal balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF_ACCOUNT.ISCARARREAR
     *
     * @mbggenerated
     */

    private BigDecimal iscararrear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF_ACCOUNT.CARARREARAMOUNT
     *
     * @mbggenerated
     */

    private BigDecimal cararrearamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF_ACCOUNT.ISACCTARREAR
     *
     * @mbggenerated
     */
    private BigDecimal isacctarrear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF_ACCOUNT.ACCTARREARAMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal acctarrearamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF_ACCOUNT.PLATFORMUSERINFO
     *
     * @mbggenerated
     */
    private String platformuserinfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF_ACCOUNT.RECORDID
     *
     * @return the value of INF_ACCOUNT.RECORDID
     *
     * @mbggenerated
     */
    public String getRecordid() {
        return recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF_ACCOUNT.RECORDID
     *
     * @param recordid the value for INF_ACCOUNT.RECORDID
     *
     * @mbggenerated
     */
    public void setRecordid(String recordid) {
        this.recordid = recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF_ACCOUNT.COMPANYCODE
     *
     * @return the value of INF_ACCOUNT.COMPANYCODE
     *
     * @mbggenerated
     */
    public String getCompanycode() {
        return companycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF_ACCOUNT.COMPANYCODE
     *
     * @param companycode the value for INF_ACCOUNT.COMPANYCODE
     *
     * @mbggenerated
     */
    public void setCompanycode(String companycode) {
        this.companycode = companycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF_ACCOUNT.CODE
     *
     * @return the value of INF_ACCOUNT.CODE
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF_ACCOUNT.CODE
     *
     * @param code the value for INF_ACCOUNT.CODE
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF_ACCOUNT.PLATE
     *
     * @return the value of INF_ACCOUNT.PLATE
     *
     * @mbggenerated
     */
    public String getPlate() {
        return plate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF_ACCOUNT.PLATE
     *
     * @param plate the value for INF_ACCOUNT.PLATE
     *
     * @mbggenerated
     */
    public void setPlate(String plate) {
        this.plate = plate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF_ACCOUNT.PLATECOLOR
     *
     * @return the value of INF_ACCOUNT.PLATECOLOR
     *
     * @mbggenerated
     */
    public BigDecimal getPlatecolor() {
        return platecolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF_ACCOUNT.PLATECOLOR
     *
     * @param platecolor the value for INF_ACCOUNT.PLATECOLOR
     *
     * @mbggenerated
     */
    public void setPlatecolor(BigDecimal platecolor) {
        this.platecolor = platecolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF_ACCOUNT.INTIME
     *
     * @return the value of INF_ACCOUNT.INTIME
     *
     * @mbggenerated
     */
    public Date getIntime() {
        return intime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF_ACCOUNT.INTIME
     *
     * @param intime the value for INF_ACCOUNT.INTIME
     *
     * @mbggenerated
     */
    public void setIntime(Date intime) {
        this.intime = intime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF_ACCOUNT.PAYEDCOMPANYCODE
     *
     * @return the value of INF_ACCOUNT.PAYEDCOMPANYCODE
     *
     * @mbggenerated
     */
    public BigDecimal getPayedcompanycode() {
        return payedcompanycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF_ACCOUNT.PAYEDCOMPANYCODE
     *
     * @param payedcompanycode the value for INF_ACCOUNT.PAYEDCOMPANYCODE
     *
     * @mbggenerated
     */
    public void setPayedcompanycode(BigDecimal payedcompanycode) {
        this.payedcompanycode = payedcompanycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF_ACCOUNT.USERID
     *
     * @return the value of INF_ACCOUNT.USERID
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF_ACCOUNT.USERID
     *
     * @param userid the value for INF_ACCOUNT.USERID
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF_ACCOUNT.TYPE
     *
     * @return the value of INF_ACCOUNT.TYPE
     *
     * @mbggenerated
     */
    public BigDecimal getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF_ACCOUNT.TYPE
     *
     * @param type the value for INF_ACCOUNT.TYPE
     *
     * @mbggenerated
     */
    public void setType(BigDecimal type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF_ACCOUNT.STATUS
     *
     * @return the value of INF_ACCOUNT.STATUS
     *
     * @mbggenerated
     */
    public BigDecimal getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF_ACCOUNT.STATUS
     *
     * @param status the value for INF_ACCOUNT.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(BigDecimal status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF_ACCOUNT.BALANCE
     *
     * @return the value of INF_ACCOUNT.BALANCE
     *
     * @mbggenerated
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF_ACCOUNT.BALANCE
     *
     * @param balance the value for INF_ACCOUNT.BALANCE
     *
     * @mbggenerated
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF_ACCOUNT.ISCARARREAR
     *
     * @return the value of INF_ACCOUNT.ISCARARREAR
     *
     * @mbggenerated
     */
    public BigDecimal getIscararrear() {
        return iscararrear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF_ACCOUNT.ISCARARREAR
     *
     * @param iscararrear the value for INF_ACCOUNT.ISCARARREAR
     *
     * @mbggenerated
     */
    public void setIscararrear(BigDecimal iscararrear) {
        this.iscararrear = iscararrear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF_ACCOUNT.CARARREARAMOUNT
     *
     * @return the value of INF_ACCOUNT.CARARREARAMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getCararrearamount() {
        return cararrearamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF_ACCOUNT.CARARREARAMOUNT
     *
     * @param cararrearamount the value for INF_ACCOUNT.CARARREARAMOUNT
     *
     * @mbggenerated
     */
    public void setCararrearamount(BigDecimal cararrearamount) {
        this.cararrearamount = cararrearamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF_ACCOUNT.ISACCTARREAR
     *
     * @return the value of INF_ACCOUNT.ISACCTARREAR
     *
     * @mbggenerated
     */
    public BigDecimal getIsacctarrear() {
        return isacctarrear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF_ACCOUNT.ISACCTARREAR
     *
     * @param isacctarrear the value for INF_ACCOUNT.ISACCTARREAR
     *
     * @mbggenerated
     */
    public void setIsacctarrear(BigDecimal isacctarrear) {
        this.isacctarrear = isacctarrear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF_ACCOUNT.ACCTARREARAMOUNT
     *
     * @return the value of INF_ACCOUNT.ACCTARREARAMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getAcctarrearamount() {
        return acctarrearamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF_ACCOUNT.ACCTARREARAMOUNT
     *
     * @param acctarrearamount the value for INF_ACCOUNT.ACCTARREARAMOUNT
     *
     * @mbggenerated
     */
    public void setAcctarrearamount(BigDecimal acctarrearamount) {
        this.acctarrearamount = acctarrearamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF_ACCOUNT.PLATFORMUSERINFO
     *
     * @return the value of INF_ACCOUNT.PLATFORMUSERINFO
     *
     * @mbggenerated
     */
    public String getPlatformuserinfo() {
        return platformuserinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF_ACCOUNT.PLATFORMUSERINFO
     *
     * @param platformuserinfo the value for INF_ACCOUNT.PLATFORMUSERINFO
     *
     * @mbggenerated
     */
    public void setPlatformuserinfo(String platformuserinfo) {
        this.platformuserinfo = platformuserinfo;
    }
}