package com.jemmyee.inf.entity;

import com.jemmyee.core.entity.BaseExample;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class ParkInfoExample extends BaseExample{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INF_PARKINFO
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INF_PARKINFO
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INF_PARKINFO
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF_PARKINFO
     *
     * @mbggenerated
     */
    public ParkInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF_PARKINFO
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF_PARKINFO
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF_PARKINFO
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF_PARKINFO
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF_PARKINFO
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF_PARKINFO
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF_PARKINFO
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF_PARKINFO
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF_PARKINFO
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF_PARKINFO
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INF_PARKINFO
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCodeIsNull() {
            addCriterion("CODE is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("CODE =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("CODE <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("CODE >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CODE >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("CODE <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("CODE <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("CODE like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("CODE not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("CODE in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("CODE not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("CODE between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("CODE not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andLatIsNull() {
            addCriterion("LAT is null");
            return (Criteria) this;
        }

        public Criteria andLatIsNotNull() {
            addCriterion("LAT is not null");
            return (Criteria) this;
        }

        public Criteria andLatEqualTo(BigDecimal value) {
            addCriterion("LAT =", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatNotEqualTo(BigDecimal value) {
            addCriterion("LAT <>", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatGreaterThan(BigDecimal value) {
            addCriterion("LAT >", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LAT >=", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatLessThan(BigDecimal value) {
            addCriterion("LAT <", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LAT <=", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatIn(List<BigDecimal> values) {
            addCriterion("LAT in", values, "lat");
            return (Criteria) this;
        }

        public Criteria andLatNotIn(List<BigDecimal> values) {
            addCriterion("LAT not in", values, "lat");
            return (Criteria) this;
        }

        public Criteria andLatBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LAT between", value1, value2, "lat");
            return (Criteria) this;
        }

        public Criteria andLatNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LAT not between", value1, value2, "lat");
            return (Criteria) this;
        }

        public Criteria andLngIsNull() {
            addCriterion("LNG is null");
            return (Criteria) this;
        }

        public Criteria andLngIsNotNull() {
            addCriterion("LNG is not null");
            return (Criteria) this;
        }

        public Criteria andLngEqualTo(BigDecimal value) {
            addCriterion("LNG =", value, "lng");
            return (Criteria) this;
        }

        public Criteria andLngNotEqualTo(BigDecimal value) {
            addCriterion("LNG <>", value, "lng");
            return (Criteria) this;
        }

        public Criteria andLngGreaterThan(BigDecimal value) {
            addCriterion("LNG >", value, "lng");
            return (Criteria) this;
        }

        public Criteria andLngGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LNG >=", value, "lng");
            return (Criteria) this;
        }

        public Criteria andLngLessThan(BigDecimal value) {
            addCriterion("LNG <", value, "lng");
            return (Criteria) this;
        }

        public Criteria andLngLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LNG <=", value, "lng");
            return (Criteria) this;
        }

        public Criteria andLngIn(List<BigDecimal> values) {
            addCriterion("LNG in", values, "lng");
            return (Criteria) this;
        }

        public Criteria andLngNotIn(List<BigDecimal> values) {
            addCriterion("LNG not in", values, "lng");
            return (Criteria) this;
        }

        public Criteria andLngBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LNG between", value1, value2, "lng");
            return (Criteria) this;
        }

        public Criteria andLngNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LNG not between", value1, value2, "lng");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("ADDRESS =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("ADDRESS <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("ADDRESS >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("ADDRESS >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("ADDRESS <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("ADDRESS <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("ADDRESS like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("ADDRESS not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("ADDRESS in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("ADDRESS not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("ADDRESS between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("ADDRESS not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andCompanycodeIsNull() {
            addCriterion("COMPANYCODE is null");
            return (Criteria) this;
        }

        public Criteria andCompanycodeIsNotNull() {
            addCriterion("COMPANYCODE is not null");
            return (Criteria) this;
        }

        public Criteria andCompanycodeEqualTo(String value) {
            addCriterion("COMPANYCODE =", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeNotEqualTo(String value) {
            addCriterion("COMPANYCODE <>", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeGreaterThan(String value) {
            addCriterion("COMPANYCODE >", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeGreaterThanOrEqualTo(String value) {
            addCriterion("COMPANYCODE >=", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeLessThan(String value) {
            addCriterion("COMPANYCODE <", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeLessThanOrEqualTo(String value) {
            addCriterion("COMPANYCODE <=", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeLike(String value) {
            addCriterion("COMPANYCODE like", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeNotLike(String value) {
            addCriterion("COMPANYCODE not like", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeIn(List<String> values) {
            addCriterion("COMPANYCODE in", values, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeNotIn(List<String> values) {
            addCriterion("COMPANYCODE not in", values, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeBetween(String value1, String value2) {
            addCriterion("COMPANYCODE between", value1, value2, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeNotBetween(String value1, String value2) {
            addCriterion("COMPANYCODE not between", value1, value2, "companycode");
            return (Criteria) this;
        }

        public Criteria andContactwayIsNull() {
            addCriterion("CONTACTWAY is null");
            return (Criteria) this;
        }

        public Criteria andContactwayIsNotNull() {
            addCriterion("CONTACTWAY is not null");
            return (Criteria) this;
        }

        public Criteria andContactwayEqualTo(String value) {
            addCriterion("CONTACTWAY =", value, "contactway");
            return (Criteria) this;
        }

        public Criteria andContactwayNotEqualTo(String value) {
            addCriterion("CONTACTWAY <>", value, "contactway");
            return (Criteria) this;
        }

        public Criteria andContactwayGreaterThan(String value) {
            addCriterion("CONTACTWAY >", value, "contactway");
            return (Criteria) this;
        }

        public Criteria andContactwayGreaterThanOrEqualTo(String value) {
            addCriterion("CONTACTWAY >=", value, "contactway");
            return (Criteria) this;
        }

        public Criteria andContactwayLessThan(String value) {
            addCriterion("CONTACTWAY <", value, "contactway");
            return (Criteria) this;
        }

        public Criteria andContactwayLessThanOrEqualTo(String value) {
            addCriterion("CONTACTWAY <=", value, "contactway");
            return (Criteria) this;
        }

        public Criteria andContactwayLike(String value) {
            addCriterion("CONTACTWAY like", value, "contactway");
            return (Criteria) this;
        }

        public Criteria andContactwayNotLike(String value) {
            addCriterion("CONTACTWAY not like", value, "contactway");
            return (Criteria) this;
        }

        public Criteria andContactwayIn(List<String> values) {
            addCriterion("CONTACTWAY in", values, "contactway");
            return (Criteria) this;
        }

        public Criteria andContactwayNotIn(List<String> values) {
            addCriterion("CONTACTWAY not in", values, "contactway");
            return (Criteria) this;
        }

        public Criteria andContactwayBetween(String value1, String value2) {
            addCriterion("CONTACTWAY between", value1, value2, "contactway");
            return (Criteria) this;
        }

        public Criteria andContactwayNotBetween(String value1, String value2) {
            addCriterion("CONTACTWAY not between", value1, value2, "contactway");
            return (Criteria) this;
        }

        public Criteria andPklottypeIsNull() {
            addCriterion("PKLOTTYPE is null");
            return (Criteria) this;
        }

        public Criteria andPklottypeIsNotNull() {
            addCriterion("PKLOTTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andPklottypeEqualTo(Short value) {
            addCriterion("PKLOTTYPE =", value, "pklottype");
            return (Criteria) this;
        }

        public Criteria andPklottypeNotEqualTo(Short value) {
            addCriterion("PKLOTTYPE <>", value, "pklottype");
            return (Criteria) this;
        }

        public Criteria andPklottypeGreaterThan(Short value) {
            addCriterion("PKLOTTYPE >", value, "pklottype");
            return (Criteria) this;
        }

        public Criteria andPklottypeGreaterThanOrEqualTo(Short value) {
            addCriterion("PKLOTTYPE >=", value, "pklottype");
            return (Criteria) this;
        }

        public Criteria andPklottypeLessThan(Short value) {
            addCriterion("PKLOTTYPE <", value, "pklottype");
            return (Criteria) this;
        }

        public Criteria andPklottypeLessThanOrEqualTo(Short value) {
            addCriterion("PKLOTTYPE <=", value, "pklottype");
            return (Criteria) this;
        }

        public Criteria andPklottypeIn(List<Short> values) {
            addCriterion("PKLOTTYPE in", values, "pklottype");
            return (Criteria) this;
        }

        public Criteria andPklottypeNotIn(List<Short> values) {
            addCriterion("PKLOTTYPE not in", values, "pklottype");
            return (Criteria) this;
        }

        public Criteria andPklottypeBetween(Short value1, Short value2) {
            addCriterion("PKLOTTYPE between", value1, value2, "pklottype");
            return (Criteria) this;
        }

        public Criteria andPklottypeNotBetween(Short value1, Short value2) {
            addCriterion("PKLOTTYPE not between", value1, value2, "pklottype");
            return (Criteria) this;
        }

        public Criteria andPklotcategoryIsNull() {
            addCriterion("PKLOTCATEGORY is null");
            return (Criteria) this;
        }

        public Criteria andPklotcategoryIsNotNull() {
            addCriterion("PKLOTCATEGORY is not null");
            return (Criteria) this;
        }

        public Criteria andPklotcategoryEqualTo(Short value) {
            addCriterion("PKLOTCATEGORY =", value, "pklotcategory");
            return (Criteria) this;
        }

        public Criteria andPklotcategoryNotEqualTo(Short value) {
            addCriterion("PKLOTCATEGORY <>", value, "pklotcategory");
            return (Criteria) this;
        }

        public Criteria andPklotcategoryGreaterThan(Short value) {
            addCriterion("PKLOTCATEGORY >", value, "pklotcategory");
            return (Criteria) this;
        }

        public Criteria andPklotcategoryGreaterThanOrEqualTo(Short value) {
            addCriterion("PKLOTCATEGORY >=", value, "pklotcategory");
            return (Criteria) this;
        }

        public Criteria andPklotcategoryLessThan(Short value) {
            addCriterion("PKLOTCATEGORY <", value, "pklotcategory");
            return (Criteria) this;
        }

        public Criteria andPklotcategoryLessThanOrEqualTo(Short value) {
            addCriterion("PKLOTCATEGORY <=", value, "pklotcategory");
            return (Criteria) this;
        }

        public Criteria andPklotcategoryIn(List<Short> values) {
            addCriterion("PKLOTCATEGORY in", values, "pklotcategory");
            return (Criteria) this;
        }

        public Criteria andPklotcategoryNotIn(List<Short> values) {
            addCriterion("PKLOTCATEGORY not in", values, "pklotcategory");
            return (Criteria) this;
        }

        public Criteria andPklotcategoryBetween(Short value1, Short value2) {
            addCriterion("PKLOTCATEGORY between", value1, value2, "pklotcategory");
            return (Criteria) this;
        }

        public Criteria andPklotcategoryNotBetween(Short value1, Short value2) {
            addCriterion("PKLOTCATEGORY not between", value1, value2, "pklotcategory");
            return (Criteria) this;
        }

        public Criteria andPklotattributeIsNull() {
            addCriterion("PKLOTATTRIBUTE is null");
            return (Criteria) this;
        }

        public Criteria andPklotattributeIsNotNull() {
            addCriterion("PKLOTATTRIBUTE is not null");
            return (Criteria) this;
        }

        public Criteria andPklotattributeEqualTo(Short value) {
            addCriterion("PKLOTATTRIBUTE =", value, "pklotattribute");
            return (Criteria) this;
        }

        public Criteria andPklotattributeNotEqualTo(Short value) {
            addCriterion("PKLOTATTRIBUTE <>", value, "pklotattribute");
            return (Criteria) this;
        }

        public Criteria andPklotattributeGreaterThan(Short value) {
            addCriterion("PKLOTATTRIBUTE >", value, "pklotattribute");
            return (Criteria) this;
        }

        public Criteria andPklotattributeGreaterThanOrEqualTo(Short value) {
            addCriterion("PKLOTATTRIBUTE >=", value, "pklotattribute");
            return (Criteria) this;
        }

        public Criteria andPklotattributeLessThan(Short value) {
            addCriterion("PKLOTATTRIBUTE <", value, "pklotattribute");
            return (Criteria) this;
        }

        public Criteria andPklotattributeLessThanOrEqualTo(Short value) {
            addCriterion("PKLOTATTRIBUTE <=", value, "pklotattribute");
            return (Criteria) this;
        }

        public Criteria andPklotattributeIn(List<Short> values) {
            addCriterion("PKLOTATTRIBUTE in", values, "pklotattribute");
            return (Criteria) this;
        }

        public Criteria andPklotattributeNotIn(List<Short> values) {
            addCriterion("PKLOTATTRIBUTE not in", values, "pklotattribute");
            return (Criteria) this;
        }

        public Criteria andPklotattributeBetween(Short value1, Short value2) {
            addCriterion("PKLOTATTRIBUTE between", value1, value2, "pklotattribute");
            return (Criteria) this;
        }

        public Criteria andPklotattributeNotBetween(Short value1, Short value2) {
            addCriterion("PKLOTATTRIBUTE not between", value1, value2, "pklotattribute");
            return (Criteria) this;
        }

        public Criteria andPklotpayruleIsNull() {
            addCriterion("PKLOTPAYRULE is null");
            return (Criteria) this;
        }

        public Criteria andPklotpayruleIsNotNull() {
            addCriterion("PKLOTPAYRULE is not null");
            return (Criteria) this;
        }

        public Criteria andPklotpayruleEqualTo(String value) {
            addCriterion("PKLOTPAYRULE =", value, "pklotpayrule");
            return (Criteria) this;
        }

        public Criteria andPklotpayruleNotEqualTo(String value) {
            addCriterion("PKLOTPAYRULE <>", value, "pklotpayrule");
            return (Criteria) this;
        }

        public Criteria andPklotpayruleGreaterThan(String value) {
            addCriterion("PKLOTPAYRULE >", value, "pklotpayrule");
            return (Criteria) this;
        }

        public Criteria andPklotpayruleGreaterThanOrEqualTo(String value) {
            addCriterion("PKLOTPAYRULE >=", value, "pklotpayrule");
            return (Criteria) this;
        }

        public Criteria andPklotpayruleLessThan(String value) {
            addCriterion("PKLOTPAYRULE <", value, "pklotpayrule");
            return (Criteria) this;
        }

        public Criteria andPklotpayruleLessThanOrEqualTo(String value) {
            addCriterion("PKLOTPAYRULE <=", value, "pklotpayrule");
            return (Criteria) this;
        }

        public Criteria andPklotpayruleLike(String value) {
            addCriterion("PKLOTPAYRULE like", value, "pklotpayrule");
            return (Criteria) this;
        }

        public Criteria andPklotpayruleNotLike(String value) {
            addCriterion("PKLOTPAYRULE not like", value, "pklotpayrule");
            return (Criteria) this;
        }

        public Criteria andPklotpayruleIn(List<String> values) {
            addCriterion("PKLOTPAYRULE in", values, "pklotpayrule");
            return (Criteria) this;
        }

        public Criteria andPklotpayruleNotIn(List<String> values) {
            addCriterion("PKLOTPAYRULE not in", values, "pklotpayrule");
            return (Criteria) this;
        }

        public Criteria andPklotpayruleBetween(String value1, String value2) {
            addCriterion("PKLOTPAYRULE between", value1, value2, "pklotpayrule");
            return (Criteria) this;
        }

        public Criteria andPklotpayruleNotBetween(String value1, String value2) {
            addCriterion("PKLOTPAYRULE not between", value1, value2, "pklotpayrule");
            return (Criteria) this;
        }

        public Criteria andPklotpic1IsNull() {
            addCriterion("PKLOTPIC1 is null");
            return (Criteria) this;
        }

        public Criteria andPklotpic1IsNotNull() {
            addCriterion("PKLOTPIC1 is not null");
            return (Criteria) this;
        }

        public Criteria andPklotpic1EqualTo(String value) {
            addCriterion("PKLOTPIC1 =", value, "pklotpic1");
            return (Criteria) this;
        }

        public Criteria andPklotpic1NotEqualTo(String value) {
            addCriterion("PKLOTPIC1 <>", value, "pklotpic1");
            return (Criteria) this;
        }

        public Criteria andPklotpic1GreaterThan(String value) {
            addCriterion("PKLOTPIC1 >", value, "pklotpic1");
            return (Criteria) this;
        }

        public Criteria andPklotpic1GreaterThanOrEqualTo(String value) {
            addCriterion("PKLOTPIC1 >=", value, "pklotpic1");
            return (Criteria) this;
        }

        public Criteria andPklotpic1LessThan(String value) {
            addCriterion("PKLOTPIC1 <", value, "pklotpic1");
            return (Criteria) this;
        }

        public Criteria andPklotpic1LessThanOrEqualTo(String value) {
            addCriterion("PKLOTPIC1 <=", value, "pklotpic1");
            return (Criteria) this;
        }

        public Criteria andPklotpic1Like(String value) {
            addCriterion("PKLOTPIC1 like", value, "pklotpic1");
            return (Criteria) this;
        }

        public Criteria andPklotpic1NotLike(String value) {
            addCriterion("PKLOTPIC1 not like", value, "pklotpic1");
            return (Criteria) this;
        }

        public Criteria andPklotpic1In(List<String> values) {
            addCriterion("PKLOTPIC1 in", values, "pklotpic1");
            return (Criteria) this;
        }

        public Criteria andPklotpic1NotIn(List<String> values) {
            addCriterion("PKLOTPIC1 not in", values, "pklotpic1");
            return (Criteria) this;
        }

        public Criteria andPklotpic1Between(String value1, String value2) {
            addCriterion("PKLOTPIC1 between", value1, value2, "pklotpic1");
            return (Criteria) this;
        }

        public Criteria andPklotpic1NotBetween(String value1, String value2) {
            addCriterion("PKLOTPIC1 not between", value1, value2, "pklotpic1");
            return (Criteria) this;
        }

        public Criteria andPklotpic2IsNull() {
            addCriterion("PKLOTPIC2 is null");
            return (Criteria) this;
        }

        public Criteria andPklotpic2IsNotNull() {
            addCriterion("PKLOTPIC2 is not null");
            return (Criteria) this;
        }

        public Criteria andPklotpic2EqualTo(String value) {
            addCriterion("PKLOTPIC2 =", value, "pklotpic2");
            return (Criteria) this;
        }

        public Criteria andPklotpic2NotEqualTo(String value) {
            addCriterion("PKLOTPIC2 <>", value, "pklotpic2");
            return (Criteria) this;
        }

        public Criteria andPklotpic2GreaterThan(String value) {
            addCriterion("PKLOTPIC2 >", value, "pklotpic2");
            return (Criteria) this;
        }

        public Criteria andPklotpic2GreaterThanOrEqualTo(String value) {
            addCriterion("PKLOTPIC2 >=", value, "pklotpic2");
            return (Criteria) this;
        }

        public Criteria andPklotpic2LessThan(String value) {
            addCriterion("PKLOTPIC2 <", value, "pklotpic2");
            return (Criteria) this;
        }

        public Criteria andPklotpic2LessThanOrEqualTo(String value) {
            addCriterion("PKLOTPIC2 <=", value, "pklotpic2");
            return (Criteria) this;
        }

        public Criteria andPklotpic2Like(String value) {
            addCriterion("PKLOTPIC2 like", value, "pklotpic2");
            return (Criteria) this;
        }

        public Criteria andPklotpic2NotLike(String value) {
            addCriterion("PKLOTPIC2 not like", value, "pklotpic2");
            return (Criteria) this;
        }

        public Criteria andPklotpic2In(List<String> values) {
            addCriterion("PKLOTPIC2 in", values, "pklotpic2");
            return (Criteria) this;
        }

        public Criteria andPklotpic2NotIn(List<String> values) {
            addCriterion("PKLOTPIC2 not in", values, "pklotpic2");
            return (Criteria) this;
        }

        public Criteria andPklotpic2Between(String value1, String value2) {
            addCriterion("PKLOTPIC2 between", value1, value2, "pklotpic2");
            return (Criteria) this;
        }

        public Criteria andPklotpic2NotBetween(String value1, String value2) {
            addCriterion("PKLOTPIC2 not between", value1, value2, "pklotpic2");
            return (Criteria) this;
        }

        public Criteria andPklotpic3IsNull() {
            addCriterion("PKLOTPIC3 is null");
            return (Criteria) this;
        }

        public Criteria andPklotpic3IsNotNull() {
            addCriterion("PKLOTPIC3 is not null");
            return (Criteria) this;
        }

        public Criteria andPklotpic3EqualTo(String value) {
            addCriterion("PKLOTPIC3 =", value, "pklotpic3");
            return (Criteria) this;
        }

        public Criteria andPklotpic3NotEqualTo(String value) {
            addCriterion("PKLOTPIC3 <>", value, "pklotpic3");
            return (Criteria) this;
        }

        public Criteria andPklotpic3GreaterThan(String value) {
            addCriterion("PKLOTPIC3 >", value, "pklotpic3");
            return (Criteria) this;
        }

        public Criteria andPklotpic3GreaterThanOrEqualTo(String value) {
            addCriterion("PKLOTPIC3 >=", value, "pklotpic3");
            return (Criteria) this;
        }

        public Criteria andPklotpic3LessThan(String value) {
            addCriterion("PKLOTPIC3 <", value, "pklotpic3");
            return (Criteria) this;
        }

        public Criteria andPklotpic3LessThanOrEqualTo(String value) {
            addCriterion("PKLOTPIC3 <=", value, "pklotpic3");
            return (Criteria) this;
        }

        public Criteria andPklotpic3Like(String value) {
            addCriterion("PKLOTPIC3 like", value, "pklotpic3");
            return (Criteria) this;
        }

        public Criteria andPklotpic3NotLike(String value) {
            addCriterion("PKLOTPIC3 not like", value, "pklotpic3");
            return (Criteria) this;
        }

        public Criteria andPklotpic3In(List<String> values) {
            addCriterion("PKLOTPIC3 in", values, "pklotpic3");
            return (Criteria) this;
        }

        public Criteria andPklotpic3NotIn(List<String> values) {
            addCriterion("PKLOTPIC3 not in", values, "pklotpic3");
            return (Criteria) this;
        }

        public Criteria andPklotpic3Between(String value1, String value2) {
            addCriterion("PKLOTPIC3 between", value1, value2, "pklotpic3");
            return (Criteria) this;
        }

        public Criteria andPklotpic3NotBetween(String value1, String value2) {
            addCriterion("PKLOTPIC3 not between", value1, value2, "pklotpic3");
            return (Criteria) this;
        }

        public Criteria andTotalnumIsNull() {
            addCriterion("TOTALNUM is null");
            return (Criteria) this;
        }

        public Criteria andTotalnumIsNotNull() {
            addCriterion("TOTALNUM is not null");
            return (Criteria) this;
        }

        public Criteria andTotalnumEqualTo(BigDecimal value) {
            addCriterion("TOTALNUM =", value, "totalnum");
            return (Criteria) this;
        }

        public Criteria andTotalnumNotEqualTo(BigDecimal value) {
            addCriterion("TOTALNUM <>", value, "totalnum");
            return (Criteria) this;
        }

        public Criteria andTotalnumGreaterThan(BigDecimal value) {
            addCriterion("TOTALNUM >", value, "totalnum");
            return (Criteria) this;
        }

        public Criteria andTotalnumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTALNUM >=", value, "totalnum");
            return (Criteria) this;
        }

        public Criteria andTotalnumLessThan(BigDecimal value) {
            addCriterion("TOTALNUM <", value, "totalnum");
            return (Criteria) this;
        }

        public Criteria andTotalnumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTALNUM <=", value, "totalnum");
            return (Criteria) this;
        }

        public Criteria andTotalnumIn(List<BigDecimal> values) {
            addCriterion("TOTALNUM in", values, "totalnum");
            return (Criteria) this;
        }

        public Criteria andTotalnumNotIn(List<BigDecimal> values) {
            addCriterion("TOTALNUM not in", values, "totalnum");
            return (Criteria) this;
        }

        public Criteria andTotalnumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTALNUM between", value1, value2, "totalnum");
            return (Criteria) this;
        }

        public Criteria andTotalnumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTALNUM not between", value1, value2, "totalnum");
            return (Criteria) this;
        }

        public Criteria andEmptynumIsNull() {
            addCriterion("EMPTYNUM is null");
            return (Criteria) this;
        }

        public Criteria andEmptynumIsNotNull() {
            addCriterion("EMPTYNUM is not null");
            return (Criteria) this;
        }

        public Criteria andEmptynumEqualTo(BigDecimal value) {
            addCriterion("EMPTYNUM =", value, "emptynum");
            return (Criteria) this;
        }

        public Criteria andEmptynumNotEqualTo(BigDecimal value) {
            addCriterion("EMPTYNUM <>", value, "emptynum");
            return (Criteria) this;
        }

        public Criteria andEmptynumGreaterThan(BigDecimal value) {
            addCriterion("EMPTYNUM >", value, "emptynum");
            return (Criteria) this;
        }

        public Criteria andEmptynumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("EMPTYNUM >=", value, "emptynum");
            return (Criteria) this;
        }

        public Criteria andEmptynumLessThan(BigDecimal value) {
            addCriterion("EMPTYNUM <", value, "emptynum");
            return (Criteria) this;
        }

        public Criteria andEmptynumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("EMPTYNUM <=", value, "emptynum");
            return (Criteria) this;
        }

        public Criteria andEmptynumIn(List<BigDecimal> values) {
            addCriterion("EMPTYNUM in", values, "emptynum");
            return (Criteria) this;
        }

        public Criteria andEmptynumNotIn(List<BigDecimal> values) {
            addCriterion("EMPTYNUM not in", values, "emptynum");
            return (Criteria) this;
        }

        public Criteria andEmptynumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("EMPTYNUM between", value1, value2, "emptynum");
            return (Criteria) this;
        }

        public Criteria andEmptynumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("EMPTYNUM not between", value1, value2, "emptynum");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Short value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Short value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Short value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Short value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Short value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Short> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Short> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Short value1, Short value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Short value1, Short value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INF_PARKINFO
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INF_PARKINFO
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}